import re
import os

def parse_ena_script(infile):
        '''
        parses the download script generated by ENA to identify 
        SRR accessions to be downloaded. Returns a dictionary of 
        sentinel file (key) and wget download command, fastq file, and 
        srr accession (list of values)
        '''

        srr_dict = {}
        with open(infile, 'r') as ena_script:
            for line in ena_script:
                line = line.rstrip("\n")
                path = line.split("/")
                # accession subdir is the second last item
                srr = path[-2]
                fq = path[-1]
                sentinel = f".sentinel.{fq}"
                srr_dict[sentinel] = [line, fq, srr]
                

        return srr_dict
