import re
import os

class ena():
    def parse_ena_script(infile):
        '''
        parses the download script generated by ENA to identify 
        SRR accessions to be downloaded. Returns a dictionary of 
        SRR accessions (key) and wget download command (values).
        Also returns a list of expected fastq files
        '''

        srr_ftp = {}
        srr_fqs = {}
        with open(infile, 'r') as ena_script:
            for line in ena_script:
                line = line.rstrip("\n")
                path = line.split("/")
                # accession subdir is the second last item
                srr = path[-2]
                fq = path[-1]

                if srr not in srr_ftp.keys():
                    srr_ftp[srr] = line
                    srr_fqs[srr] = fq
                else:
                    srr_ftp[srr].append(line)
                    srr_fqs[srr].append(os.path.join(srr, fq))

        return srr_ftp, srr_fqs