# set job options for md5sum
md5sum:
  job_threads: 1
  job_memory: 15G

# set job options for zstd
zstd:
  job_threads: 8
  job_memory: 1G
  # set compression level
  compression_lvl: 22
  # set true or false, if true will delete .gz files within input.dir
  remove_input_files: false